lsi: false
safe: true
source: /
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
title: /MattiasLindberg
description: This is a site using Markdown files.
theme: simplex  # Optional: use a Jekyll theme
